name: Pull Request
on:
  pull_request:
jobs:
  pr-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Enable corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn --immutable

      - name: Pr check
        run: yarn pr-check
